// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9EVLDHqQQQl0r6UbA0A84fCmRH2o2ht4',
    appId: '1:267467914482:web:5642995fc52b309506646b',
    messagingSenderId: '267467914482',
    projectId: 'medzone-84ccc',
    authDomain: 'medzone-84ccc.firebaseapp.com',
    storageBucket: 'medzone-84ccc.firebasestorage.app',
    measurementId: 'G-QJ5XBTYBQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1JLWMfEaSdI6kWBaGHufQC1qZjZyFu7g',
    appId: '1:267467914482:android:e14e74ec2d6b26ac06646b',
    messagingSenderId: '267467914482',
    projectId: 'medzone-84ccc',
    storageBucket: 'medzone-84ccc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzIi6NwaROxA8BmIO2ULCMyFWGFkHdD0o',
    appId: '1:267467914482:ios:b93f6aa4b6d7ffc506646b',
    messagingSenderId: '267467914482',
    projectId: 'medzone-84ccc',
    storageBucket: 'medzone-84ccc.firebasestorage.app',
    iosBundleId: 'com.example.medliy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzIi6NwaROxA8BmIO2ULCMyFWGFkHdD0o',
    appId: '1:267467914482:ios:b93f6aa4b6d7ffc506646b',
    messagingSenderId: '267467914482',
    projectId: 'medzone-84ccc',
    storageBucket: 'medzone-84ccc.firebasestorage.app',
    iosBundleId: 'com.example.medliy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9EVLDHqQQQl0r6UbA0A84fCmRH2o2ht4',
    appId: '1:267467914482:web:01955e383e1ee6da06646b',
    messagingSenderId: '267467914482',
    projectId: 'medzone-84ccc',
    authDomain: 'medzone-84ccc.firebaseapp.com',
    storageBucket: 'medzone-84ccc.firebasestorage.app',
    measurementId: 'G-J0GKYYNZV2',
  );
}
